---
- name: Audyt zainstalowanych pakietów
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: true
  vars_files:
    - packages.yml

  vars:
    report_file: "/tmp/audit_report_{{ inventory_hostname }}_{{ ansible_date_time.date }}.txt"
    local_report_dir: "{{ playbook_dir }}"

  tasks:
    - name: Sprawdź wersje pakietów (Debian/Ubuntu)
      ansible.builtin.shell: |
        dpkg-query -W -f='${Package}|${Version}|${Status}\n' {{ item }} 2>/dev/null || echo "{{ item }}|NIE ZAINSTALOWANY|unknown"
      loop: "{{ packages }}"
      register: package_versions_deb
      changed_when: false
      failed_when: false
      when: ansible_os_family == "Debian"

    - name: Sprawdź wersje pakietów (RedHat/CentOS)
      ansible.builtin.shell: |
        rpm -q --queryformat '%{NAME}|%{VERSION}-%{RELEASE}|installed\n' {{ item }} 2>/dev/null || echo "{{ item }}|NIE ZAINSTALOWANY|unknown"
      loop: "{{ packages }}"
      register: package_versions_rpm
      changed_when: false
      failed_when: false
      when: ansible_os_family == "RedHat"

    - name: Ustaw wyniki pakietów (Debian)
      ansible.builtin.set_fact:
        package_results: "{{ package_versions_deb.results }}"
      when: ansible_os_family == "Debian"

    - name: Ustaw wyniki pakietów (RedHat)
      ansible.builtin.set_fact:
        package_results: "{{ package_versions_rpm.results }}"
      when: ansible_os_family == "RedHat"

    - name: Generuj raport na zdalnym hoście
      ansible.builtin.template:
        src: templates/report.j2
        dest: "{{ report_file }}"
        mode: '0644'

    - name: Wyświetl lokalizację raportu
      ansible.builtin.debug:
        msg: "Raport zapisany: {{ report_file }}"

    - name: Pobierz raport na lokalny serwer
      ansible.builtin.fetch:
        src: "{{ report_file }}"
        dest: "{{ local_report_dir }}/reports/"
        flat: false

    - name: Informacja o pobranym raporcie
      ansible.builtin.debug:
        msg: "Raport skopiowany do: {{ local_report_dir }}/reports/{{ inventory_hostname }}{{ report_file }}"
